version: "3.8"

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hrs
    ports:
      - 5432:5432

  hrs-api:
    image: bmlueiza/hrsapi:reallatest
    container_name: hrs-api
    ports:
      - 8000:8000
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db

  hrs-web:
    image: bmlueiza/hrsweb:reallatest
    container_name: hrs-web
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - hrs-api
