from .diagnostico import Diagnostico
from .gestor import Gestor
from .paciente import Paciente
from .motivo import Motivo
from .medico import Medico
from .medicamento import Medicamento
from .actividad_medica import ActividadMedica
from .accion_gestor import AccionGestor
from .resultado_contacto import ResultadoContacto
from .historial_contacto import HistorialContacto
from .recomendacion import Recomendacion
from .observacion import Observacion
from .asignacion_actividad import AsignacionActividad
from .historial_medicamento import HistorialMedicamento
