# Generated by Django 4.2.6 on 2023-11-27 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=12, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=25)),
                ('apellido2', models.CharField(max_length=25)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.IntegerField(choices=[(0, 'No especificado'), (1, 'Masculino'), (2, 'Femenino'), (9, 'No aplicable')])),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=50)),
                ('riesgo', models.IntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto')])),
                ('diagnosticos', models.ManyToManyField(blank=True, null=True, related_name='pacientes', to='hrsapp.diagnostico')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='hrsapp.gestor')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('etiqueta', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('accion_gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='hrsapp.acciongestor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='hrsapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=250)),
                ('fecha_generacion', models.DateField()),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_gestor', to='hrsapp.paciente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='hrsapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('freq_administracion', models.CharField(blank=True, max_length=50, null=True)),
                ('dosis', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Al día'), (2, 'No retirado'), (2, 'Terminado'), (3, 'Suspendido')])),
                ('ultimo_retiro', models.DateField(blank=True, null=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_medicamento', to='hrsapp.medicamento')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_medicamento', to='hrsapp.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_medicamento', to='hrsapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('accion_gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_contacto', to='hrsapp.acciongestor')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hc_gestor', to='hrsapp.paciente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_contacto', to='hrsapp.paciente')),
                ('resultado_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_contacto', to='hrsapp.resultadocontacto')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('fecha_realizacion', models.DateField()),
                ('estado', models.IntegerField(choices=[(1, 'Asignada'), (2, 'Realizada'), (3, 'Cancelada')])),
                ('actividad_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_medicas', to='hrsapp.actividadmedica')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_medicas', to='hrsapp.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_medicas', to='hrsapp.paciente')),
            ],
        ),
    ]
