# Generated by Django 4.2.6 on 2023-10-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='diagnostico',
            new_name='diagnosticos',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos',
            field=models.ManyToManyField(to='hrsapp.medicamento'),
        ),
    ]
