# Generated by Django 4.2.6 on 2023-11-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='diagnosticos',
            field=models.ManyToManyField(related_name='pacientes', to='hrsapp.diagnostico'),
        ),
    ]
