# Generated by Django 4.2.6 on 2023-10-27 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0002_medicamento_rename_diagnostico_paciente_diagnosticos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='diagnosticos',
            new_name='id_diagnosticos',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='gestor',
            new_name='id_gestor',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicamentos',
        ),
        migrations.CreateModel(
            name='SeguimientoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('resultado', models.CharField(max_length=50)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrsapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrsapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
                ('id_gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestor_responsable', to='hrsapp.paciente')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='hrsapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrsapp.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrsapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('dosis', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('ultimo_retiro', models.DateField()),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrsapp.medicamento')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrsapp.paciente')),
            ],
        ),
    ]
