# Generated by Django 4.2.6 on 2023-10-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0003_medico_rename_diagnosticos_paciente_id_diagnosticos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionmedicamento',
            old_name='id_medicamento',
            new_name='medicamento',
        ),
        migrations.RenameField(
            model_name='asignacionmedicamento',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='id_medico',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='observacion',
            old_name='id_gestor',
            new_name='gestor',
        ),
        migrations.RenameField(
            model_name='observacion',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='id_diagnosticos',
            new_name='diagnosticos',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='id_gestor',
            new_name='gestor',
        ),
        migrations.RenameField(
            model_name='seguimientopaciente',
            old_name='id_paciente',
            new_name='paciente',
        ),
    ]
