# Generated by Django 4.2.6 on 2023-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0003_alter_medicamento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
