# Generated by Django 4.2.6 on 2023-10-27 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0004_rename_id_medicamento_asignacionmedicamento_medicamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionmedicamento',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrsapp.medico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observacion',
            name='gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestor_id', to='hrsapp.paciente'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrsapp.paciente'),
        ),
    ]
