# Generated by Django 4.2.6 on 2023-11-28 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0004_alter_medicamento_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Actividad médica'), (2, 'Medicamento'), (3, 'Diagnóstico')])),
            ],
        ),
        migrations.RenameField(
            model_name='resultadocontacto',
            old_name='etiqueta',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='historialmedicamento',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='historialmedicamento',
            name='freq_administracion',
        ),
        migrations.AddField(
            model_name='acciongestor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historialmedicamento',
            name='administracion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historialmedicamento',
            name='cantd_otorgada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acciongestor',
            name='codigo',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='actividadmedica',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historialcontacto',
            name='motivo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='historial_contacto', to='hrsapp.motivo'),
            preserve_default=False,
        ),
    ]
