# Generated by Django 4.2.6 on 2023-11-28 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0005_motivo_rename_etiqueta_resultadocontacto_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='motivo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='hrsapp.motivo'),
            preserve_default=False,
        ),
    ]
