# Generated by Django 4.2.6 on 2023-10-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0005_asignacionmedicamento_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
