# Generated by Django 4.2.6 on 2023-11-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0006_recomendacion_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='apellido',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
