# Generated by Django 4.2.6 on 2023-10-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0006_alter_paciente_rut_alter_paciente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='medico',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
