# Generated by Django 4.2.6 on 2023-12-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0007_alter_medico_apellido_alter_medico_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadmedica',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones', to='hrsapp.gestor'),
        ),
    ]
