# Generated by Django 4.2.6 on 2023-12-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0008_alter_actividadmedica_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadocontacto',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='gestor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pacientes', to='hrsapp.gestor'),
        ),
    ]
