# Generated by Django 4.2.6 on 2023-12-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0009_remove_resultadocontacto_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acciongestor',
            name='codigo',
        ),
    ]
