# Generated by Django 4.2.6 on 2023-12-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0010_remove_acciongestor_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadmedica',
            name='codigo',
        ),
    ]
