# Generated by Django 4.2.6 on 2023-12-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0011_remove_actividadmedica_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionactividad',
            old_name='fecha_realizacion',
            new_name='fecha_actividad',
        ),
        migrations.AlterField(
            model_name='asignacionactividad',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Asignada'), (2, 'Realizada'), (3, 'Cancelada'), (4, 'No realizada')]),
        ),
    ]
