# Generated by Django 4.2.6 on 2023-12-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsapp', '0012_rename_fecha_realizacion_asignacionactividad_fecha_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactividad',
            name='hora_actividad',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
